#' Functions to identify reviewer-applicant pairs from incomplete block design
#'
#' @param x A design generated by `assignReviewers()`
#' @param appNames A vector of applicant names
#' @return A matrix of applicant assignments. Each row corresponds with the applicants assigned to each reviewer, so the number of rows should correspond with the number of reviewers. The number of columns corresponds to the parameter `alternatives.per.block` used in `assignReviewers()`.
#' @examples
#' \dontrun{
#' s.des.names = getAssignments(x = student.design,
#'                              appNames = applicantNames)
#' }
#' @export
# 



# A function to extract names from applicant info using the sampling design output from incomplete.block.design()
# incomplete.block.design() returns all assignments as numbers that refer to the order of names in the source data. This function enables keeping names with numbers.
nameFinder = function(x, applNames){
  return(unlist(applNames[x,]))
}


# A function to extract the reviewer assignments from the incomplete block design. Here, x is a design generated from incomplete.block.design(). 
getAssignments = function(x, appNames){
  myDesign = t(x$design)
  # fill in applicant names to student reviewer and faculty reviewer tables
  myDesNames = apply(myDesign,
                     MARGIN = c(1,2),
                     FUN = nameFinder,
                     applNames = appNames)
}

