#' A function to extract names from applicant info using the sampling design output from incomplete.block.design(). This is an internal function and users will not directly interact with it.
#'
#' @param x A single element in the design generated by `assignReviewers()`
#' @param applNames A vector of applicant names
#' @return A vector of applicant assignments.
#' @examples
#' \dontrun{
#' outNames = nameFinder(x, applNames)
#' }
#' @export
# 


# incomplete.block.design() returns all assignments as numbers that refer to the order of names in the source data. This function enables keeping names with numbers.
nameFinder = function(x, applNames){
  return(unlist(applNames[x]))
}

